# Acknowlegment
# Author V. Kamakoti
# Department of Computer Science and Engineering
# IIT Madras
####################

### TOP_DIR: The Ddirectory containing the .bsv file
### TOP_FILE: The Name of the file that contains the topmost module
### TOP_MODULE: The Name of the topmost module which will be defined inside the TOP_FILE
### MODULE: This is the name of the python test bench WITHOUT the (.py) extension


TOP_MODULE:=noc
TOP_FILE:=noc.bsv
TOP_DIR:=.
MODULE:=noc_sim
#Above is the python testbench name without .py extension
